blank_issues_enabled: false
contact_links:
  - name: Immuni Feature Request
    url: https://github.com/immuni-app/documentation
    about: Please open a feature request in the appropriated repository as defined in the CONTRIBUTING file
